from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.units import cm
from datetime import datetime
import os

class ReportGenerator:
    def __init__(self, output_dir="reports"):
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)

    def generate_pdf(self, vehicle_info, diagnostic_results, issues):
        """
        สร้างรายงาน PDF ภาษาไทย
        """
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"report_{vehicle_info['vin']}_{timestamp}.pdf"
        filepath = os.path.join(self.output_dir, filename)
        
        c = canvas.Canvas(filepath, pagesize=A4)
        width, height = A4
        
        # Header
        c.setFont("Helvetica-Bold", 20)
        c.drawCentredString(width/2, height - 2*cm, "Toyota Diagnostic Pro")
        
        c.setFont("Helvetica", 12)
        c.drawCentredString(width/2, height - 2.8*cm, f"Diagnostic Report - {datetime.now().strftime('%Y-%m-%d %H:%M')}")
        
        # Vehicle Info Section
        c.line(1*cm, height - 3.5*cm, width - 1*cm, height - 3.5*cm)
        c.setFont("Helvetica-Bold", 14)
        c.drawString(1.5*cm, height - 4.2*cm, "Vehicle Information")
        
        c.setFont("Helvetica", 11)
        y = height - 5*cm
        c.drawString(2*cm, y, f"VIN: {vehicle_info['vin']}")
        c.drawString(2*cm, y - 0.6*cm, f"Model: {vehicle_info['model']}")
        c.drawString(2*cm, y - 1.2*cm, f"Year: {vehicle_info['year']}")
        c.drawString(2*cm, y - 1.8*cm, f"Engine: {vehicle_info['engine_type']}")
        
        # Diagnostic Summary
        c.setFont("Helvetica-Bold", 14)
        c.drawString(1.5*cm, y - 3*cm, "Diagnostic Summary")
        
        y_issue = y - 3.8*cm
        if not issues:
            c.setFont("Helvetica", 11)
            c.drawString(2*cm, y_issue, "No critical issues detected. System is healthy.")
        else:
            c.setFont("Helvetica", 11)
            for issue in issues:
                c.drawString(2*cm, y_issue, f"- {issue['Symptom']}")
                c.setFont("Helvetica-Oblique", 9)
                c.drawString(2.5*cm, y_issue - 0.4*cm, f"Recommendation: {issue['Recommendation']}")
                y_issue -= 1.2*cm
                if y_issue < 3*cm:
                    c.showPage()
                    y_issue = height - 3*cm
        
        # Footer
        c.setFont("Helvetica", 8)
        c.drawCentredString(width/2, 1*cm, "Generated by Toyota Diagnostic Pro Engine")
        
        c.save()
        return filepath
